### ISSUE TITLE
Update rxdart to 0.24.0

### ISSUE THREAD

**Issue by Reprevise** [davidsdearaujo/select_dialog#14]
It's not too much of an issue since I just override the version manually, but it would be great if you upgraded the rxdart dependency.

**Comment by angwandi** [comment]
Because select_dialog >=1.0.7 depends on rxdart ^0.23.1 and flutter_form_bloc 0.14.0 depends on rxdart ^0.24.0, select_dialog >=1.0.7 is incompatible with flutter_form_bloc 0.14.0.

please any fix?

**Comment by joankabello** [comment]
Please update rxdart to 0.24.0

**Comment by joankabello** [comment]
> It's not too much of an issue since I just override the version manually, but it would be great if you upgraded the rxdart dependency.

@Reprevise How did you do that ?

**Comment by Reprevise** [comment]
See here: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by davidsdearaujo** [comment]
Updated in pullrequest #17
