### ISSUE TITLE
Update rxdart to ^0.24.1

### ISSUE THREAD

**Issue by DevyankShaw** [davidsdearaujo/select_dialog#20]
Facing the below issue: 
`Because select_dialog >=1.0.7 depends on rxdart ^0.23.1 and flutter_plugin_pdf_viewer 1.0.7 depends on rxdart ^0.24.1, select_dialog >=1.0.7 is incompatible with flutter_plugin_pdf_viewer 1.0.7.
And because no versions of flutter_plugin_pdf_viewer match >1.0.7 <2.0.0, select_dialog >=1.0.7 is incompatible with flutter_plugin_pdf_viewer ^1.0.7.`

**Comment by davidsdearaujo** [comment]
Updated in pullrequest #17
