### ISSUE TITLE
barrierDismissable Not Working

### ISSUE THREAD

**Issue by MaheshaGubbiOrg** [davidsdearaujo/select_dialog#23]
The named parameter 'barrierDismissable' isn't defined
![image](https://user-images.githubusercontent.com/39371199/91028186-b943fc00-e61a-11ea-9157-ed79d75422f5.png)

**Comment by vinceramcesoliveros** [comment]
Please read my instructions here:
https://github.com/ram231/select_dialog
While this issues hasn't been fixed. this fork enables barrierDismissable property when you show a dialog.

**Comment by davidsdearaujo** [comment]
Hi @ram231 
It will be of great help if you contribute to the package by sending a pull-request of these changes to the main project
