### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by domenicrz** [davidsdearaujo/select_dialog#33]
Hi everyone,

I would like to help your project by adding some features like:
- Reset Button (I have already implemented this one)
- Visualise selected items before in multi selection mode (Done this too)

If you are interested please tell me 👍

Regards

**Comment by awasum** [comment]
Go ahead and send a PR.

**Comment by domenicrz** [comment]
Any news on pull Requests?

**Comment by machadoapoena** [comment]
> 
I need those ...where is the code? the last version does not has
