### ISSUE TITLE
Error After Flutter Upgrade

### ISSUE THREAD

**Issue by mmmaxi** [davidsdearaujo/select_dialog#8]
After Upgrading to the latest flutter stable release 1.12.3 my project is not buildable anymore because of the following error:

`../flutter/.pub-cache/hosted/pub.dartlang.org/select_dialog-1.0.6+1/lib/select_bloc.dart:9:3: Error: 'Observable' isn't a type.
  Observable<List<T>> _filteredListOnlineOut;`

**Comment by yanqiqi1996** [comment]
@mmmaxi  I have the same problem ,Do you have anyway to solve it
