### ISSUE TITLE
Error: Type 'Observable' not found

### ISSUE THREAD

**Issue by zangen** [davidsdearaujo/select_dialog#9]
I had this problem today,could   you help me solve it?

Compiler message:
../../Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/find_dropdown-0.1.7+1/lib/find_dropdown_bloc.dart:9:3: Error: Type 'Observable' not found.
  Observable<String> get validateMessageOut => _validateMessage$;
  ^^^^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/find_dropdown-0.1.7+1/lib/find_dropdown_bloc.dart:9:3: Error: Expected 0 type arguments.
  Observable<String> get validateMessageOut => _validateMessage$;
  ^
../../Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/select_dialog-1.0.6+1/lib/select_bloc.dart:8:3: Error: Type 'Observable' not found.
  Observable<List<T>> filteredListOut;
  ^^^^^^^^^^
../../Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/select_dialog-1.0.6+1/lib/select_bloc.dart:8:3: Error: Expected 0 type arguments.
  Observable<List<T>> filteredListOut;

**Comment by micdoug** [comment]
It seems that it is a breaking change on rxdart package. I also experienced this problem and I was able to solve it by fixing the rxdart package version in pubspec.yaml to 0.22.2.
In the change https://github.com/ReactiveX/rxdart/commit/b0edb3d0b2adfb8245b6692623c2ae863c8b520c they changed the Observable type behavior. A note in the commit `Move all Rx operators from Observable to *Extension`.
